# Valid search engines:
# 'Google (google.com)'
# 'Yahoo (yahoo.com)'
# 'custom' (see comment below)
searchEngine = 'Yahoo (yahoo.com)'

# If searchEngine is set to 'custom', then set customUrl
# to the homepage url of your preferred search engine.
# customUrl = ''

colorMode = 'light'
